### ISSUE TITLE
merovius.de/go-misc/gjsfs: Does it do anything differently than gopherjs_http.NewFS?

### ISSUE THREAD

**Issue by dmitshur** [Merovius/go-misc#1]
Hi @Merovius,

I found your `merovius.de/go-misc/gjsfs` package and I just wanted to ask a question in order to learn more about it.

Is it in any way differentiated from https://godoc.org/github.com/shurcooL/go/gopherjs_http#NewFS, or does it offer equivalent functionality?

I'm looking to refactor that and perhaps consolidate it with the internal `http.FileSystem` implementation that `gopherjs` has for `gopherjs serve` command, so I wanted to see if there's something here that isn't already offered elsewhere.

Thanks!

**Comment by dmitshur** [comment]
No response, so I understand this project is no longer being maintained (please feel free to reopen otherwise). Thanks anyway.

**Comment by Merovius** [comment]
I think it is fair to say that I don't maintain this hobby project very well :)

Apparently, there is about a 4-day difference between the two being committed, so it is perfectly possible that I didn't know about the other implementation when I did mine (I honestly don't remember). I don't assume I do things fundamentally better than them, so if I had to decide again whether to add this, I might not do it.

**Comment by dmitshur** [comment]
Gotcha, thanks.

**Comment by dmitshur** [comment]
Just as a heads up, @Merovius, your package imports `github.com/shurcooL/gopherjslib` package:

https://godoc.org/github.com/shurcooL/gopherjslib?importers 

I will be moving that import path soon. If you want your code to continue working, you'll just have to update the import path to the new one (it's quick and easy).

I'll post an update here when that happens, I just wanted to give you an advance warning.

**Comment by Merovius** [comment]
Thanks for the heads up :)
